<h2>Dynamic Array as Index of DataFrame</h2>

In [1]:
data_1=['Tom','Jack','Steve','Ricky']
myList = [f'man{x+1}' for x in range(len(data_1))]
print(myList)

['man1', 'man2', 'man3', 'man4']


<h2>DataFrame 與 Series</h2>

In [8]:
import pandas as pd
data=['Tom','Jack','Steve','Ricky']
print('List:\n', data)
print('='*50)
df=pd.DataFrame(data) #DataFrame可以有多個Columns，而Columns都會有索引標籤
print('DataFrame:\n', df)
print('='*50)
s1=pd.Series(data) #Series只有一個Column
print('Series:\n', s1)
print('='*50)
myIndex = [f'man{x+1}' for x in range(len(data))]
df2=pd.DataFrame(data,index=myIndex, columns=['Names'])
print('DataFrame with index and column:\n', df2)
print('='*50)

List:
 ['Tom', 'Jack', 'Steve', 'Ricky']
DataFrame:
        0
0    Tom
1   Jack
2  Steve
3  Ricky
Series:
 0      Tom
1     Jack
2    Steve
3    Ricky
dtype: object
DataFrame with index and column:
       Names
man1    Tom
man2   Jack
man3  Steve
man4  Ricky


<h2>Combine 2 Lists to DataFrame</h2>

In [9]:
import pandas as pd
groups=['Python','Django','Sqlite','Numpy','Security','Pandas']
numbers=[59,9,19,14,6,77]
# mydict = {'Python': 59, 'Django': 9, 'Sqlite': 19, 'Numpy': 14, 'Security': 6, 'Pandas': 77}
# print(mydict)
# combine 2 lists into a dictionary
mydict2 = {'XGroup': groups, 'XNumber': numbers}
df = pd.DataFrame(mydict2)
print(df)

     XGroup  XNumber
0    Python       59
1    Django        9
2    Sqlite       19
3     Numpy       14
4  Security        6
5    Pandas       77


<h2>Two dimension array</h2>

In [10]:
lst = [[0,1,2], [3,4,5], [6,7,8]]
print(lst)
print("Type: ", type(lst))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
Type:  <class 'list'>


<h2>Numpy N-dimensional array</h2>

In [11]:
import numpy as np
import pandas as pd
mynp = np.arange(12).reshape(4,3)
print(mynp)
print(type(mynp))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>


In [12]:
df_1 = pd.DataFrame(mynp, index=['A', 'B', 'C', 'D'], columns=['X','Y','Z'])
print(df_1)
print(type(df_1))

   X   Y   Z
A  0   1   2
B  3   4   5
C  6   7   8
D  9  10  11
<class 'pandas.core.frame.DataFrame'>
